#### Table 1

In [0]:
%sql
DROP TABLE Products

In [0]:
%sql
CREATE TABLE if not exists Products(
  Product_name varchar(30),
  Issue_date double,
  Price int,
  Brand varchar(30),
  Country varchar(30),
  product_number int 
  );

In [0]:
%sql
show create table Products

createtab_stmt
"CREATE TABLE `default`.`Products` ( `Product_name` VARCHAR(30), `Issue_date` DOUBLE, `Price` INT, `Brand` VARCHAR(30), `Country` VARCHAR(30), `product_number` INT) USING delta"

In [0]:
%sql
insert into Products values("Washing Machine",1648770933000 , 20000, "Samsung", "India", 0001),
                            ("Refrigerator", 1648770999000 ,35000, "     LG","null",0002),
                            ("Air Cooler", 1648770948000, 45000,"     Voltas", "null", 0003)

num_affected_rows,num_inserted_rows
3,3

In [0]:
%sql
select * from Products

Product_name,Issue_date,Price,Brand,Country,product_number
Washing Machine,1.648770933E12,20000,Samsung,India,1
Air Cooler,1.648770948E12,45000,Voltas,null,3
Refrigerator,1.648770999E12,35000,LG,null,2

In [0]:
import pandas as pd

In [0]:
df = _sqldf.toPandas()
print(df)

In [0]:
from datetime import datetime as dt

In [0]:
def timestamp():
    df['Issue_date'] = df['Issue_date'].apply(lambda x: dt.fromtimestamp(x/1000))
    return df['Issue_date']

In [0]:
timestamp()

In [0]:
df['Date'] = df["Issue_date"].dt.date

In [0]:
df

,Product_name,Issue_date,Price,Brand,Country,product_number,Date
0,Washing Machine,2022-03-31 23:55:33,20000,Samsung,India,1,2022-03-31
1,Air Cooler,2022-03-31 23:55:48,45000,Voltas,null,3,2022-03-31
2,Refrigerator,2022-03-31 23:56:39,35000,LG,null,2,2022-03-31

In [0]:
def space():
    df['Brand'] = df['Brand'].apply(lambda x: x.lstrip())
    return df['Brand']

In [0]:
space()

In [0]:
df

,Product_name,Issue_date,Price,Brand,Country,product_number,Date
0,Washing Machine,2022-03-31 23:55:33,20000,Samsung,India,1,2022-03-31
1,Air Cooler,2022-03-31 23:55:48,45000,Voltas,null,3,2022-03-31
2,Refrigerator,2022-03-31 23:56:39,35000,LG,null,2,2022-03-31

In [0]:
df['Country']=="null"

In [0]:
def null(col):
    df[col] = df[col].apply(lambda x: x.replace("null", " ") if "null" in x else x)
    return df[col]

In [0]:
null('Country')

In [0]:
df

,Product_name,Issue_date,Price,Brand,Country,product_number,Date
0,Washing Machine,2022-03-31 23:55:33,20000,Samsung,India,1,2022-03-31
1,Air Cooler,2022-03-31 23:55:48,45000,Voltas,,3,2022-03-31
2,Refrigerator,2022-03-31 23:56:39,35000,LG,,2,2022-03-31

#### Table 2

In [0]:
%sql
drop table data_transaction

In [0]:
%sql
create table data_transaction(
  SourceID int,
  TransactionNumber int,
  Language varchar(15),
  ModelNumber int,
  StartTime varchar(50),
  ProductNumber int
);

In [0]:
%sql
select * from data_transaction

In [0]:
%sql
insert into data_transaction VALUES (150711, 123456, "EN", 456789, "2021-12-27T08:20:29.842+0000", 0001),
                                    (150439, 234567, "UK", 345678, "2021-12-27T08:21:14.645+0000", 0002),
                                    (150647, 345678, "ES", 234567, "2021-12-27T08:22:42.445+0000", 0003)

num_affected_rows,num_inserted_rows
3,3

In [0]:
%sql
select * from data_transaction

SourceID,TransactionNumber,Language,ModelNumber,StartTime,ProductNumber
150711,123456,EN,456789,2021-12-27T08:20:29.842+0000,1
150439,234567,UK,345678,2021-12-27T08:21:14.645+0000,2
150647,345678,ES,234567,2021-12-27T08:22:42.445+0000,3

In [0]:
trans_df = _sqldf.toPandas()
trans_df

,SourceID,TransactionNumber,Language,ModelNumber,StartTime,ProductNumber
0,150711,123456,EN,456789,2021-12-27T08:20:29.842+0000,1
1,150439,234567,UK,345678,2021-12-27T08:21:14.645+0000,2
2,150647,345678,ES,234567,2021-12-27T08:22:42.445+0000,3

In [0]:
trans_df.dtypes

<p>a)    Change the camel case columns to snake case <br>
Example: SourceId: source_id, TransactionNumber: transaction_number
</p>

In [0]:
import re

In [0]:
columns = trans_df.columns.to_list()
def split_uppercase():
    for i in columns:
        column_split = re.findall("[a-zA-Z][^A-Z]*",i)
        underscore_split = "_".join(column_split).lower()
        trans_df.rename(columns= {i:underscore_split}, inplace=True)
    return trans_df

In [0]:
split_uppercase()

,source_i_d,transaction_number,language,model_number,start_time,product_number
0,150711,123456,EN,456789,2021-12-27T08:20:29.842+0000,1
1,150439,234567,UK,345678,2021-12-27T08:21:14.645+0000,2
2,150647,345678,ES,234567,2021-12-27T08:22:42.445+0000,3

<p>b)	Add another column as start_time_ms and convert the values of StartTime to milliseconds.</p>

In [0]:
trans_df['start_time'] = pd.to_datetime(trans_df['start_time'])

In [0]:
from datetime import datetime

In [0]:
trans_df['start_time']

In [0]:
def date_timestamp(col):
    for i in trans_df[col]:
        trans_df[col] = datetime.timestamp(i)
    return trans_df

In [0]:
date_timestamp("start_time")

,source_i_d,transaction_number,language,model_number,start_time,product_number
0,150711,123456,EN,456789,1.640593e+09,1
1,150439,234567,UK,345678,1.640593e+09,2
2,150647,345678,ES,234567,1.640593e+09,3

<p>3.	Combine both the tables based on the Product Number <br>
•	    and get all the fields in return.<br>
•	    And get the country as EN <br>
</p>

In [0]:
df_final = pd.merge(trans_df, df, on='product_number').set_index("product_number")
df_final

,source_i_d,transaction_number,language,model_number,start_time,Product_name,Issue_date,Price,Brand,Country,Date
product_number,,,,,,,,,,,
1,150711,123456,EN,456789,1.640593e+09,Washing Machine,2022-03-31 23:55:33,20000,Samsung,India,2022-03-31
2,150439,234567,UK,345678,1.640593e+09,Refrigerator,2022-03-31 23:56:39,35000,LG,,2022-03-31
3,150647,345678,ES,234567,1.640593e+09,Air Cooler,2022-03-31 23:55:48,45000,Voltas,,2022-03-31

In [0]:
df_final[df_final['language'] == "EN"]

,source_i_d,transaction_number,language,model_number,start_time,Product_name,Issue_date,Price,Brand,Country,Date
product_number,,,,,,,,,,,
1,150711,123456,EN,456789,1.640593e+09,Washing Machine,2022-03-31 23:55:33,20000,Samsung,India,2022-03-31